pipeline {
    agent any
    
    environment{
        SCANNER_HOME= tool "sonar"
    }

    stages {
        stage('Clean Workspace ') {
            steps {
                echo "Cleaning Workspace:"
                cleanWs()
            }
        }
        
        stage("Code Checkout"){
            steps{
                git url: "https://github.com/Nehabisen21/TWSThreeTierAppChallenge.git", branch: "main"
            }
        }
        
        stage("Sonarqube Analysis"){
            steps{
                withSonarQubeEnv("sonar"){
                 sh '''$SCANNER_HOME/bin/sonar-scanner -Dsonar.projectKey=threetierapp -Dsonar.projectName=threetierapp'''
                }
            }
        }
    }
}
